<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2020/11/12
 * Time: 11:24
 */
namespace app\v2\controller;

use app\common\controller\AdminBase;
use app\common\model\Contact as contatctModel;
use app\v2\validate\ContactValidate;

/**
 * Class Contact
 * @package app\v2\controller
 * 联系我们控制器
 */
class Contact extends AdminBase
{


    protected $model ='';

    protected $validate ='';


    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub

        $this->model = new contatctModel();
        $this->validate = new ContactValidate();
    }


    public function create()
    {
        return $this->fetch();
    }



}